#------------------------------------------------------------------------------ 
#---# General

# Tell Tmux to that the terminal emulator supports 256 colors.
set -g default-terminal "screen-256color"

#------------------------------------------------------------------------------ 
#---# Key Bindings

bind-key | split-window -h
bind-key - split-window

#------------------------------------------------------------------------------ 
#---# Windows and Panes

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Do not allow Tmux to automatically rename windows.
set-option -g allow-rename off

#------------------------------------------------------------------------------ 
#---# Plug-ins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'odedlaz/tmux-onedark-theme'

# Initialize Tmux plugin manager (keep this line at the very bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

